### PR TITLE
Add Docker things

### PR DESCRIPTION
**Pull request by travnewmatic**
Tested on x86 and Raspberry Pi 4, both work.

### CODE REVIEW

**Comment by travnewmatic** [comment]
- should make a mechanism to pull the `latest` deb from github releases
- probably things can be stripped out to make the image smaller
- goal was to get to a minimum viable prototype, can refine things later, but it does run

**Comment by jxmx** [comment]
@travnewmatic - Is this ready to go?

**Comment by travnewmatic** [comment]
It works for me, but I encourage you to use it on your end first to see if it behaves like you expect it to.  Also it might be good make it grab whatever the latest Deb is.  Currently it's grabbing a specific version (the most recent available at the time I was working on this).

**Comment by jxmx** [comment]
Like I said, I don't do anything with Docker.

**Pull request merged**
